apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-api-secrets
  namespace: ecommerce
  labels:
    app: ecommerce-api
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  SECRET_KEY: "${APP_SECRET_KEY}"
  STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
  STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
